// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('FAQ2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('FAQ2', async function() {
    // Test name: FAQ2
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://file-sharing-dev.netlify.app/")
    // 2 | setWindowSize | 1340x722 | 
    await driver.manage().window().setRect({ width: 1340, height: 722 })
    // 3 | click | css=.text-customFaq | 
    await driver.findElement(By.css(".text-customFaq")).click()
    // 4 | click | css=#radix-\3Ar0\3A > .lucide | 
    await driver.findElement(By.css("#radix-\\3Ar0\\3A > .lucide")).click()
  })
})
