// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
// Імпортуємо модулі з Selenium WebDriver:
// - `Builder` використовується для створення екземпляра WebDriver.
// - `By` дозволяє знаходити елементи на сторінці.
// - `until` надає умови очікування.
// - `Key` дозволяє використовувати спеціальні клавіші клавіатури.

const assert = require('assert')
// Імпортуємо бібліотеку `assert` для виконання перевірок (assertions) в тестах.

describe('jpg1', function() {
  this.timeout(30000)
  // Встановлюємо тайм-аут для тестів у 30 секунд.

  let driver
  let vars

  beforeEach(async function() {
    driver = await new Builder().forBrowser('MicrosoftEdge').build()
    // Створюємо екземпляр WebDriver для браузера Chrome.
    vars = {}
    // Ініціалізуємо змінну `vars`.
  })

  afterEach(async function() {
    await driver.quit();
    // Завершуємо роботу WebDriver, щоб закрити браузер і звільнити ресурси.
  })

  it('jpg1', async function() {
    await driver.get("https://file-sharing-dev.netlify.app/")

    // Завантажуємо вказану веб-сторінку в браузері.
    await driver.sleep(1000)
    await driver.manage().window().setRect({ width: 1340, height: 722 })
    // Встановлюємо розмір вікна браузера на ширину 1340 пікселів і висоту 722 пікселі.
    await driver.sleep(1000)
    await driver.findElement(By.css(".min-w-fit")).click()
    // Знаходимо елемент з класом `.min-w-fit` і виконуємо клік на нього.
    await driver.sleep(1000)
    await driver.findElement(By.css(".border")).sendKeys("C:\Users\ok-la\OneDrive\Desktop\IT\nest\file-sharing-tests\test_files")
    // Знаходимо елемент з класом `.border` і вводимо шлях до файлу `C:\\fakepath\\avtomobil_sinij_sportkar_883083_1400x1050.jpg`.
    await driver.sleep(1000)
    await driver.findElement(By.css(".end")).click()
    // Знаходимо елемент з класом `.end` і виконуємо клік на нього.
  })
})
