// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('jpg2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('MicrosoftEdge').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('jpg2', async function() {
    // Test name: jpg2
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://file-sharing-dev.netlify.app/")
    // 2 | setWindowSize | 1340x722 | 
    await driver.manage().window().setRect({ width: 1340, height: 722 })
    // 3 | click | css=.min-w-fit | 
    await driver.findElement(By.css(".min-w-fit")).click()
    // 4 | type | css=.border | C:\Users\ok-la\OneDrive\Desktop\IT\nest\file-sharing-tests\123.jpg
    await driver.findElement(By.css(".border")).sendKeys("C:\Users\ok-la\OneDrive\Desktop\IT\nest\file-sharing-tests\test_files")
   
    // 5 | click | css=.end | 
    await driver.findElement(By.css(".end")).click()
  })
})
